using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ActivatePointer : MonoBehaviour
{
    public GameObject objetoAActivar;
    public Color colorAlColisionar = Color.red; // Establecer el color de colisi贸n como rojo
    private Renderer rend;
    private Color colorOriginal;

    private void Start()
    {
        rend = GetComponent<Renderer>();
        colorOriginal = rend.material.color; // Guardar el color original al inicio
    }

    void Update()
    {
        // Verifica si se ha presionado la tecla P
        if (Input.GetKeyDown(KeyCode.P))
        {
            // Cambia el estado activo/inactivo del objeto
            objetoAActivar.SetActive(!objetoAActivar.activeSelf);
            Debug.Log("Se presion贸 la tecla P");
        }
    }

    private void OnCollisionEnter(Collision collision)
    {
        // Cambiar el color del objeto cuando colisiona con otro objeto
        rend.material.color = colorAlColisionar;
        Debug.Log("Colision贸 con " + collision.gameObject.name);
    }

    private void OnCollisionExit(Collision collision)
    {
        // Restaurar el color original al dejar de colisionar
        rend.material.color = colorOriginal;
        Debug.Log("Dej贸 de colisionar con " + collision.gameObject.name);
    }
}
